### ISSUE TITLE
DB Error in Parameters

### ISSUE THREAD

**Issue by SidKondapuram** [openmpp/main#2]
Description:
Working on a microsimulation model to test policy ideas on the Canadian retirement income system.

Issue:
Unable to use the most recent release of the Linux version of OpenM++ to build and execute our existing models. Attached is the error message we receive when trying to use it.

<img width="868" alt="Screen Shot 2021-06-09 at 10 39 03 AM" src="https://user-images.githubusercontent.com/28262280/121365340-f0b43880-c90e-11eb-8658-ff3e316d6bcc.png">

**Comment by amc1999** [comment]
* Is it a Linux specific issue? Or same error happen on MacOS and Windows?
* Is this a last release problem? Or same error happen in previous release?
* Do you want us to check why type #123 does not exist in type dictionary? 
If yes then please send us a link to git clone the model. 
If this is a private repository then please communicate over support email _openmpp dot org at gmail dot com_ to avoid publishing confidential information.

**Comment by amc1999** [comment]
It looks like problem already discussed with your colleagues, please contact them (and us, if necessary) for hot fix solution.
